### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by Bortus-AI** [mwlistscom/getvod#2]
Permissions are correct but still getting an error

~/media $ php getvod.php
Download : https://xxxxxxxxxxxxxxx/VODTV
PHP Warning:  fopen(/home/nav/media/ttps://xxxxx/iptv/xxxxx/xxxxxxx/VODTV-rockmym3u.strm): Failed to open stream: No such file or directory in /mnt/mpathaj/nav/media/getvod.php on line 120
Error opening STRM file for write ! Check working directory permissions !

**Comment by mwlistscom** [comment]
Is that a real directory? (busy at work last qtr - but I have time to fix a few bugs this week) lmk if any other issues 

/home/nav/media/ttps://xxxxx/iptv/xxxxx/xxxxxxx/

**Comment by mwlistscom** [comment]
We released a new Repository that works on multiple OS that's easier to maintian. 

https://github.com/mwlistscom/GetSTRM/releases/tag/v1.0.2

There are no plans to update GetVOD going forward
